### ISSUE TITLE
Error communicating with HID device: TypeError: Cannot write to hid device

### ISSUE THREAD

**Issue by monster4866** [C4/Fuelband-Connect#2]
`packet sent
[
  0,  1, 32,  1,  64,  0,  0, 0, 0, 0,  0, 0,
  0,  0,  0,  0, 162, 49, 41, 0, 0, 0,  0, 0,
  0, 32, 17, 20,   1,  4,  0, 0, 9, 2, 58, 2,
  0,  0,  0,  0,   0,  0,  0, 0, 0, 0,  0, 0,
  0,  0,  0,  0,   0,  0,  0, 0, 0, 0,  0, 0,
  0,  0,  0,  0,   0,  0,  0, 0, 0, 0,  0, 0,
  0,  0,  0,  0,   0,  0,  0, 0, 0, 0,  0, 0,
  0,  0,  0,  0,   0,  0,  0, 0, 0, 0,  0, 0
]
Error communicating with HID device: TypeError: Cannot write to hid device
    at doInitSE (/Users/macbook/Downloads/Fuelband-Connect-main/main.js:384:16)
    at /Users/macbook/Downloads/Fuelband-Connect-main/main.js:665:13
    at async node:electron/js2c/browser_init:2:98042
`

this error is in the console if i try u restore the fuelband to a working state, all other functions works fine

**Comment by theodorecharles** [comment]
Same issue. I can write individual values and read them but I can't use the factory reset or initialize functions. 

```
Error communicating with HID device: TypeError: Cannot write to hid device
    at doInitSE (/Users/ted/Desktop/Fuelband-Connect/main.js:384:16)
    at /Users/ted/Desktop/Fuelband-Connect/main.js:665:13
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:78381)
```

**Comment by monster4866** [comment]
i have not found any soulutions yet :/ any advise?

**Comment by Jackgame281** [comment]
I currently don't have advice, but I'm posting here so I can share a similar issue. I can't read from the FuelBand, as every data field comes up as 'undefined'. 
`Error communicating with HID device: TypeError: Cannot write to hid device
    at getModelNumber (C:\Users\jackg\Documents\GitHub\Fuelband-Connect\main.js:237:12)
    at C:\Users\jackg\Documents\GitHub\Fuelband-Connect\main.js:586:35
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:86542)
`
However, I can see part of the band up in the original software but not much else. Any ideas?
